# Generated by Django 4.0.1 on 2022-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
