# Generated by Django 4.0.1 on 2022-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='isIncome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
